name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger for any changes in Python scripts in the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      # Install dependencies for all scripts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3 python-dotenv pandas numpy textblob  # Install all required packages

      - name: Determine changed scripts
        id: check-scripts
        run: |
          echo "Finding changed scripts..."
          changed_scripts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/.*\.py' || true)

          if [ -z "$changed_scripts" ]; then
            echo "No valid scripts to run"
            echo "scripts_changed=false" >> $GITHUB_ENV
          else
            echo "Changed scripts: $changed_scripts"
            echo "$changed_scripts" >> $GITHUB_ENV
            echo "scripts_changed=true" >> $GITHUB_ENV
          fi

      - name: Run the Script
        if: env.scripts_changed == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          for script in $(echo "${{ env.changed_scripts }}"); do
            case "$script" in
              Scripts/reddit_batch_processing.py) python "$script" ;;
              Scripts/reddit_kinesis_1.py) python "$script" ;;
              Scripts/kinesis_processing_2.py) python "$script" ;;
              Scripts/reddit_lambda.py) python "$script" ;;
              *) echo "No valid script to run: $script" ;;
            esac
          done
