name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger for any changes in Python scripts in the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      # Install dependencies for all scripts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3 python-dotenv pandas numpy textblob  # Install all required packages

      - name: Run the Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          case $GITHUB_EVENT_PATH in
            *reddit_batch_processing.py*) python Scripts/reddit_batch_processing.py ;;
            *reddit_kinesis_1.py*) python Scripts/reddit_kinesis_1.py ;;
            *kinesis_processing_2.py*) python Scripts/kinesis_processing_2.py ;;
            *reddit_lambda.py*) python Scripts/reddit_lambda.py ;;
            *) echo "No valid script to run" ;;
          esac
