name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger for any changes in Python files within the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Determine changed scripts
        id: check-scripts
        run: |
          echo "Finding changed scripts..."
          # Get changed scripts using git diff
          changed_scripts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/.*\.py' || true)

          if [ -z "$changed_scripts" ]; then
            echo "No valid scripts to run"
            echo "scripts_changed=false" >> $GITHUB_ENV
          else
            echo "Changed scripts: $changed_scripts"
            echo "scripts_changed=true" >> $GITHUB_ENV
            echo "$changed_scripts" >> $GITHUB_ENV
          fi

      - name: Run changed scripts
        if: env.scripts_changed == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  # Set your AWS region
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  # Add these as secrets
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          for script in $(echo "${{ env.changed_scripts }}"); do
            echo "Running $script..."
            python "$script"
          done
