name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/**'  # Trigger for any changes in the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Determine changed scripts
        id: check-scripts
        run: |
          echo "Finding changed scripts..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/*.py' > changed_scripts.txt
          if [[ -s changed_scripts.txt ]]; then
            echo "Scripts changed: $(cat changed_scripts.txt)"
            echo "scripts_changed=true" >> $GITHUB_ENV
            # Set the script to run, for example, the first changed script
            echo "script=$(head -n 1 changed_scripts.txt)" >> $GITHUB_ENV
          else
            echo "No valid scripts to run"
            echo "scripts_changed=false" >> $GITHUB_ENV
          fi

      - name: Run the Script
        if: env.scripts_changed == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  # Set your AWS region
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  # Add these as secrets
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python Scripts/${{ env.script }}  # Run the script selected from the changed scripts
