name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/**'  # Trigger for any changes in the Scripts directory

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      - name: Set Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-north-1" >> $GITHUB_ENV
          echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "REDDIT_USER_AGENT=${{ secrets.REDDIT_USER_AGENT }}" >> $GITHUB_ENV

  run_scripts:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - { name: 'Reddit Batch Processing', path: 'Scripts/reddit_batch_processing.py', deps: 'praw boto3' }
          - { name: 'Reddit Kinesis Stream 1', path: 'Scripts/reddit_kinesis_1.py', deps: 'praw boto3 python-dotenv' }
          - { name: 'Kinesis Processing 2', path: 'Scripts/kinesis_processing_2.py', deps: 'boto3 pandas textblob numpy' }
          - { name: 'Reddit Lambda', path: 'Scripts/reddit_lambda.py', deps: 'boto3' }

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.script.deps }}

      - name: Run Script
        run: |
          python ${{ matrix.script.path }}
        if: contains(github.event.head_commit.modified, matrix.script.path)
