name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger for changes in any Python script in the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest version of Python 3

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3 python-dotenv pandas numpy textblob  # Install all required packages

      # Determine if specific scripts were changed
      - name: Check for changed scripts
        id: check-scripts
        run: |
          echo "Checking for changed scripts..."

          # Get the list of changed Python scripts
          changed_scripts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/.*\.py' || true)

          # Initialize flags for script changes
          reddit_kinesis_changed=false
          kinesis_processing_changed=false
          other_scripts_changed=false

          # Check for specific script changes
          for script in $changed_scripts; do
            case "$script" in
              Scripts/reddit_kinesis_1.py) reddit_kinesis_changed=true ;;
              Scripts/kinesis_processing_2.py) kinesis_processing_changed=true ;;
              *) other_scripts_changed=true ;;
            esac
          done

          # Set environment variable based on changes detected
          if $reddit_kinesis_changed && $kinesis_processing_changed; then
            echo "scripts_changed=both" >> $GITHUB_ENV
          elif $reddit_kinesis_changed; then
            echo "scripts_changed=reddit_only" >> $GITHUB_ENV
          elif $kinesis_processing_changed; then
            echo "scripts_changed=kinesis_only" >> $GITHUB_ENV
          elif $other_scripts_changed; then
            echo "scripts_changed=other_changed" >> $GITHUB_ENV
          else
            echo "scripts_changed=false" >> $GITHUB_ENV
          fi

      # Execute both scripts if both were changed
      - name: Execute Reddit Kinesis Scripts
        if: env.scripts_changed == 'both'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          echo "Running reddit_kinesis_1.py and kinesis_processing_2.py..."
          python Scripts/reddit_kinesis_1.py
          python Scripts/kinesis_processing_2.py

      # Handle the case where only reddit_kinesis_1.py was changed
      - name: Notify on Only reddit_kinesis_1.py Change
        if: env.scripts_changed == 'reddit_only'
        run: |
          echo "Notice: reddit_kinesis_1.py was changed, but kinesis_processing_2.py was not. Both scripts should be updated together."

      # Handle the case where only kinesis_processing_2.py was changed
      - name: Notify on Only kinesis_processing_2.py Change
        if: env.scripts_changed == 'kinesis_only'
        run: |
          echo "Notice: kinesis_processing_2.py was changed, but reddit_kinesis_1.py was not. Both scripts should be updated together."

      # Notify when other scripts are changed
      - name: Notify on Other Script Changes
        if: env.scripts_changed == 'other_changed'
        run: |
          echo "Other scripts have been changed, but neither reddit_kinesis_1.py nor kinesis_processing_2.py were affected."

      # Notify when no relevant scripts were changed
      - name: Notify on No Relevant Script Changes
        if: env.scripts_changed == 'false'
        run: |
          echo "No relevant Reddit scripts were changed in this commit."
