name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger on changes in any Python script within the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest version of Python 3

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3 python-dotenv pandas numpy textblob  # Install all required packages

      # Determine which scripts were changed
      - name: Check for changed scripts
        id: check-scripts
        run: |
          changed_scripts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/.*\.py' || true)
          echo "Changed scripts: $changed_scripts"  # Debug line

          # Initialize flags for script changes
          reddit_kinesis_changed=false
          kinesis_processing_changed=false
          reddit_batch_processing_changed=false
          reddit_lambda_changed=false
          dynamodb_processing_changed=false
          reddit_stream_processing_changed=false
          other_scripts_changed=false

          # Update flags based on changed scripts
          for script in $changed_scripts; do
            case "$script" in
              Scripts/reddit_kinesis_1.py) reddit_kinesis_changed=true ;;
              Scripts/kinesis_processing_2.py) kinesis_processing_changed=true ;;
              Scripts/reddit_batch_processing.py) reddit_batch_processing_changed=true ;;
              Scripts/reddit_lambda.py) reddit_lambda_changed=true ;;
              Scripts/dynamodb_processing.py) dynamodb_processing_changed=true ;;
              Scripts/reddit_stream_processing.py) reddit_stream_processing_changed=true ;;
              *) other_scripts_changed=true ;;
            esac
          done

          # Set environment variable for changed scripts
          if $reddit_kinesis_changed && $kinesis_processing_changed; then
            echo "scripts_changed=both_kinesis" >> $GITHUB_ENV
          elif $reddit_kinesis_changed; then
            echo "scripts_changed=reddit_kinesis_only" >> $GITHUB_ENV
          elif $kinesis_processing_changed; then
            echo "scripts_changed=kinesis_only" >> $GITHUB_ENV
          elif $reddit_batch_processing_changed; then
            echo "scripts_changed=reddit_batch_only" >> $GITHUB_ENV
          elif $reddit_lambda_changed; then
            echo "scripts_changed=reddit_lambda_only" >> $GITHUB_ENV
          elif $dynamodb_processing_changed; then
            echo "scripts_changed=dynamodb_processing_only" >> $GITHUB_ENV
          elif $reddit_stream_processing_changed; then
            echo "scripts_changed=reddit_stream_processing_only" >> $GITHUB_ENV
          elif $other_scripts_changed; then
            echo "scripts_changed=other_changed" >> $GITHUB_ENV
          else
            echo "scripts_changed=false" >> $GITHUB_ENV
          fi

      # Run Reddit Batch Processing Script
      - name: Run Reddit Batch Processing Script
        if: env.scripts_changed == 'reddit_batch_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running reddit_batch_processing.py..."
          python Scripts/reddit_batch_processing.py

      # Run Reddit Kinesis and Kinesis Processing Scripts if both are changed
      - name: Run Reddit Kinesis and Kinesis Processing Scripts
        if: env.scripts_changed == 'both_kinesis'  # Only run if both scripts are changed
        run: |
          echo "Running reddit_kinesis_1.py and kinesis_processing_2.py..."
          python Scripts/reddit_kinesis_1.py
          python Scripts/kinesis_processing_2.py

      # Run Reddit Kinesis 1 Script if it was changed but kinesis_processing_2.py was not
      - name: Run Reddit Kinesis 1 Script
        if: env.scripts_changed == 'reddit_kinesis_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running reddit_kinesis_1.py..."
          python Scripts/reddit_kinesis_1.py

      # Run Kinesis Processing 2 Script if it was changed but reddit_kinesis_1.py was not
      - name: Run Kinesis Processing 2 Script
        if: env.scripts_changed == 'kinesis_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running kinesis_processing_2.py..."
          python Scripts/kinesis_processing_2.py

      # Run Reddit Lambda Script
      - name: Run Reddit Lambda Script
        if: env.scripts_changed == 'reddit_lambda_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running reddit_lambda.py..."
          python Scripts/reddit_lambda.py

      # Run DynamoDB Processing Script
      - name: Run DynamoDB Processing Script
        if: env.scripts_changed == 'dynamodb_processing_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running dynamodb_processing.py..."
          python Scripts/dynamodb_processing.py

      # Run Reddit Stream Processing Script
      - name: Run Reddit Stream Processing Script
        if: env.scripts_changed == 'reddit_stream_processing_only' || env.scripts_changed == 'other_changed'
        run: |
          echo "Running reddit_stream_processing.py..."
          python Scripts/reddit_stream_processing.py

      # Notify when no relevant scripts were changed
      - name: Notify on No Relevant Script Changes
        if: env.scripts_changed == 'false'
        run: echo "No relevant Reddit scripts were changed in this commit."
