name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'reddit_batch_processing.py'  # Only trigger when this file changes

jobs:
  run-reddit-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3  # Install required Python packages

      - name: Run Reddit Batch Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  # Set your AWS region
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  # Add these as secrets
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}  
        run: |
          python reddit_batch_processing.py
