name: Reddit Data Pipeline

on:
  push:
    paths:
      - 'Scripts/*.py'  # Trigger for any changes in Python scripts in the Scripts directory

jobs:
  run-reddit-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      # Install dependencies for all scripts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw boto3 python-dotenv pandas numpy textblob  # Install all required packages

      - name: Determine changed script
        id: script
        run: |
          # Find the changed scripts
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Scripts/*.py' > changed_scripts.txt
          if [ -s changed_scripts.txt ]; then
            SCRIPT=$(cat changed_scripts.txt)
            echo "SCRIPT=$SCRIPT" >> $GITHUB_ENV  # Set the script as an environment variable
          else
            echo "No valid script to run" && exit 1  # Exit with an error if no scripts found
          fi

      - name: Run the Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'  # Set your AWS region
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  # Add these as secrets
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          if [ -n "$SCRIPT" ]; then
            python "$SCRIPT"  # Run the detected script
          else
            echo "No valid script to run" && exit 1
          fi
